#!/usr/bin/env zsh

if [ -f $1 ]; then
  cat $1 | \
  tr '\t' ' ' | \
  tr '’' "'" | \
  tr '‘' "'" | \
  tr '“' '"' | \
  tr '”' '"' | \
  tr '（' '(' | \
  tr '）' ')' | \
  tr '【' '[' | \
  tr '】' ']' | \
  tr '，' ', ' | \
  tr '、' ', ' | \
  tr '。' '. ' | \
  tr '；' '; ' | \
  tr '：' ': ' | \
  tr '！' '! ' | \
  tr '？' '? ' > \
  $1
else
  echo "$1 does not exist."
fi
